### ISSUE TITLE
powershell RDP script working only locally & not from Terraform

### ISSUE THREAD

**Issue by amirdaniely** [amirdaniely/terraform_playground#7]
locals {
  regkey = "HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Terminal Server/WinStations/RDP-tcp"
  change_rdp_port_command = "Set-ItemProperty ${local.regkey} -name PortNumber -value ${var.rdpport}"
  install_telnet_command   = "Add-WindowsFeature telnet-client"
  install_chrome_command = "$Path = $env:TEMP; $Installer = 'chrome_installer.exe'; Invoke-WebRequest 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile $Path$Installer; Start-Process -FilePath $Path$Installer -Args '/silent /install' -Verb RunAs -Wait; Remove-Item $Path$Installer"
  powershell_command   = "${local.change_rdp_port_command};${local.install_telnet_command};${local.install_chrome_command};"
}

 settings = <<SETTINGS
    {
      "commandToExecute": "powershell.exe -Command \"${local.powershell_command}\""    
       
    }
SETTINGS

**Comment by amird-rnd** [comment]
fixed
